- name: Install benchmarker
  command: /home/isucon/local/go/bin/go build -o bin/benchmarker cmd/bench/main.go
  args:
    chdir: /home/isucon/isucari
  environment:
    GO111MODULE: "on"
  become: yes
  become_user: isucon
