- name: Create isucari directory
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/isucari
    state=directory

- name: Deploy isucari
  become: yes
  become_user: isucon
  synchronize:
    src: ../../../../
    dest: /home/isucon/isucari
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=go.mod"
      - "--exclude=go.sum"
      - "--exclude=bench"
      - "--exclude=cmd"
      - "--exclude=LICENCE"
      - "--exclude=Makefile"
      - "--exclude=provisioning"
      - "--exclude=initial-data"

- name: Chown isucon
  become: yes
  become_user: root
  file:
    dest: /home/isucon/isucari
    owner: isucon
    group: isucon
    mode: 0755
    recurse: yes
