- name: Create isucon_admin group
  group:
    name: isucon_admin
    gid: 1002
    state: present
    system: no

- name: Create isucon_admin user
  user:
    name: isucon_admin
    uid: 1002
    group: isucon_admin
    password: isucon_admin
    home: /home/isucon_admin
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  copy:
    content: "isucon_admin  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-admin-user
    owner: root
    group: root
    mode: 0440

- name: Create dot ssh directory
  become: yes
  file:
    path: /home/isucon_admin/.ssh
    state: directory
    owner: isucon_admin
    group: isucon_admin
    mode: 0700

- name: Copy admin public keys to authorized_keys
  copy:
    src: authorized_keys
    dest: /home/isucon_admin/.ssh/authorized_keys
    owner: isucon_admin
    group: isucon_admin
    mode: 0600
