- name: Create isucon_admin group
  group:
    name: isucon_admin
    gid: 1002
    state: present
    system: no

- name: Create isucon_admin user
  user:
    name: isucon_admin
    uid: 1002
    group: isucon_admin
    password: isucon_admin
    home: /home/isucon_admin
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  copy:
    content: "isucon_admin  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-admin-user
    owner: root
    group: root
    mode: 0440
