- hosts: localhost
  user: root
  gather_facts: yes
  vars_prompt:
    - name: "target"
      prompt: "Target: vagrant or local?"
      default: "vagrant"

  roles:
    - bootstrap
    - users.isucon
    - users.isucon_admin

    - { role: vagrant-specific, when: target == "vagrant" }

    - kernel-tune
    - nginx
    - nginx.log-format
    - golang
    - external.nginx
    - external.benchmarker
    - external.shipment
    - external.payment
    # TODO
    # - benchmark-worker

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - shipment.service
        - payment.service
