- hosts: localhost
  user: root
  gather_facts: yes

  roles:
    - bootstrap
    - external.deploy

    - kernel-tune
    - nginx
    - nginx.log-format
    - golang
    - external.nginx
    - external.shipment
    - external.payment
    - external.benchmarker
    # TODO
    # - benchmark-worker

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - shipment.service
        - payment.service
