- hosts: dev
  user: root
  become: yes
  gather_facts: yes

  roles:
    - user.isucon
    - bootstrap
    - dev.deploy

    - kernel-tune
    - golang
    - external.shipment
    - external.payment

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - shipment.service
        - payment.service
