- hosts: webapp
  user: root
  gather_facts: yes

  roles:
    - user.isucon
    - user.isucon_admin
    - bootstrap
    - webapp.deploy

    - nginx
    - mysql
    - golang
    - perl
    - webapp.mysql
    - webapp.golang
    - webapp.perl
    - webapp.nginx

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - mysql.service
        - isucari.golang.service
